INSERT INTO Recipe(Name,Location,Details,Image,Category,Population,Latitude,Longitude) VALUES 
    ('The Big One','Africa & Asia','A hamburger, beefburger or burger is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, or flame broiled.','http://i.imgur.com/YMSNPvs.jpg','burger',10000,-8.783195,34.508523),
    ('Mock Dog','Central & South America','The hot dog or dog is a grilled or steamed link-sausage sandwich where the sausage is served in the slit of a special hot dog bun, a partially sliced bun. It can also refer to just the sausage of its composition. Typical sausages include wiener, frankfurter, or knackwurst.','https://i.chzbgr.com/full/6474099968/h9EE24576/','hotdog',23000,12.769013,-85.602364),
    ('Data cake','Central and East Africa','Cake is a form of sweet dessert that is typically baked. In their oldest forms, cakes were modifications of breads, but cakes now cover a wide range of preparations that can be simple or elaborate, and that share features with other desserts such as pastries, meringues, custards, and pies.','https://c1.staticflickr.com/3/2523/3704845236_8cf4d84013.jpg','cake',12000,1.957709,37.297204),
    ('Pie Bite','Central & South America','Cake is a form of sweet dessert that is typically baked. In their oldest forms, cakes were modifications of breads, but cakes now cover a wide range of preparations that can be simple or elaborate, and that share features with other desserts such as pastries, meringues, custards, and pies.','https://puppetcircuits.files.wordpress.com/2010/05/img_4705.jpg','cake',11000,-8.783195,-55.491477),
    ('Burger with NuGet','Brazil','A hamburger, beefburger or burger is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, or flame broiled.','https://5.imimg.com/data5/BE/JR/GLADMIN-40426501/chicken-nuggets-500x500.png','burger',19000,-14.235004,-51.92528),
    ('Pizza & Prod','South America','Pizza is a savory dish of Italian origin, consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and various other ingredients baked at a high temperature, traditionally in a wood-fired oven.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXjIv3lHEpjy1GWV_GZ-Eoc9XIkXQcHLF8ChK2WkNzoMibrhwm','pizza',8000,-8.783195,-55.491477),
    ('Jelly bugs','Japan','Jelly beans are small bean-shaped sugar candies with soft candy shells and thick gel interiors. The confection is sold in a wide variety of colors and flavors, and is made primarily of sugar.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/JellyBellyBeans.jpg/1200px-JellyBellyBeans.jpg','sweets',1000,36.204824,138.252924),
    ('The framewok','Southern Cameroon, Gabon, Equatorial Guinea, and Congo','A wok pan is a versatile round-bottomed cooking vessel, originating from China. The use of the wok is very prevalent in South China. It is one of the most common cooking utensils in China and also found in parts of East, South and Southeast Asia, as well as becoming a popular niche cookware in all the world. ','https://media-cdn.tripadvisor.com/media/photo-s/0c/d1/b5/18/le-wok-au-bewok.jpg','asian',17000,7.369722,12.354722),
    ('Spaghetti code','Borneo','Also commonly used to refer to the variety dishes made with it, pasta is typically made from an unleavened dough of a durum wheat flour mixed with water or eggs, and formed into sheets or various shapes, then cooked by boiling or baking. Some pastas can be made using rice flour in place of wheat flour to yield a different taste and texture, or for those who need to avoid products containing gluten.','https://sourcemaking.com/files/sm/images/spagett.jpg','pasta',15000,0.961883,114.55485),
    ('Infinite meat loop','Seattle','Meat is animal flesh that is eaten as food. Humans have hunted and killed animals for meat since prehistoric times. The advent of civilization allowed the domestication of animals such as chickens, sheep, rabbits, pigs and cattle.','https://thespinoff.co.nz/wp-content/uploads/2018/04/mad3.jpg','meat',1,47.606209,-122.332071),
    ('Asp DotNuts','Phoenix','A doughnut or donut is a type of fried dough confection or dessert food. The doughnut is popular in many countries and prepared in various forms as a sweet snack that can be homemade or purchased in bakeries, supermarkets, food stalls, and franchised specialty vendors.','https://static.cuisineaz.com/400x320/i135737-donuts-a-l-americaine.jpeg','cake',1,33.448377,-112.074037),
    ('Double Mock-Dog with interfaces','Southern Cameroon, Gabon, Equatorial Guinea, and Congo','The hot dog or dog is a grilled or steamed link-sausage sandwich where the sausage is served in the slit of a special hot dog bun, a partially sliced bun. It can also refer to just the sausage of its composition. Typical sausages include wiener, frankfurter, or knackwurst.','https://eatingrichly.com/wp-content/uploads/2017/07/hot-dog-race-cars-9724-800x533.jpg','hotdog',1,7.369722,12.354722);
